version: '2'
services:
  web:
    build: .
    command: /bin/start.sh ${DJ_APP}
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
